
DROP TABLE "MVHS"."QUITTUNG" ;

CREATE TABLE "MVHS"."QUITTUNG" 
   (	"VNR" VARCHAR2(12 BYTE), 
	"SEMESTER" VARCHAR2(1 BYTE), 
	"TNR" NUMBER(8,0), 
	"STATUS" VARCHAR2(1 BYTE), 
	"ERMAESS" VARCHAR2(1 BYTE), 
	"GESAMTK" NUMBER(9,2), 
	"ZAHLWEISE" VARCHAR2(1 BYTE), 
	"BEZAHLT" NUMBER(9,2), 
	"KENNZ" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"SYSDATUM" VARCHAR2(17 BYTE), 
	"BESTAETIGUNG" VARCHAR2(1 BYTE), 
	"RECHNR" NUMBER(8,0), 
	"SOLLSATZ" VARCHAR2(1 BYTE), 
	"VSTATUS" VARCHAR2(1 BYTE), 
	"JAHR" VARCHAR2(2 BYTE), 
	"TTY" VARCHAR2(15 BYTE), 
	"MAHNDATUM_1" DATE, 
	"MAHNBETRAG_1" NUMBER(9,2), 
	"MAHNDATUM_2" DATE, 
	"MAHNBETRAG_2" NUMBER(9,2), 
	"MAHNDATUM_3" DATE, 
	"MAHNBETRAG_3" NUMBER(9,2), 
	"MAHNDATUM_4" DATE, 
	"MAHNBETRAG_4" NUMBER(9,2), 
	"KEY_VNR" NUMBER(8,0), 
	"MAHNSPERRE" VARCHAR2(1 BYTE), 
	"USR_ID" VARCHAR2(30 BYTE), 
	"USR_DATUM" DATE, 
	"FIRMA_NR" NUMBER(8,0), 
	"BEMERKUNG" VARCHAR2(60 BYTE), 
	"PARTNER" VARCHAR2(1 BYTE), 
	"ZUSATZK" NUMBER(8,2), 
	"BERECHNUNGSGRENZE" DATE, 
	"FAELLIG_AM" DATE, 
	"RATENBEGINN" DATE, 
	"RATENENDE" DATE, 
	"RECH_DATUM" DATE, 
	"RECH_BETRAG" NUMBER(9,2), 
	"MAHN_NR" NUMBER(8,0), 
	"PARTNER_TNR" NUMBER(8,0), 
	"ABZUEGL" NUMBER(8,2), 
	"RATE" NUMBER(8,2), 
	"KEY_VTAGE" NUMBER(12,0), 
	"KEY_QUITTUNG" NUMBER(12,0), 
	"AUFTRAG_NR" NUMBER(8,0), 
	"KONTINGENT" VARCHAR2(1 BYTE), 
	"MENGE" NUMBER(4,0), 
	"ZAHL_PFLICHTIG" NUMBER(8,0), 
	"WER_ZAHLT" VARCHAR2(1 BYTE), 
	"WER_ERHAELT" VARCHAR2(1 BYTE), 
	"WER_ANSPRECHPARTNER" VARCHAR2(1 BYTE), 
	"WER_ENTSENDET" VARCHAR2(1 BYTE), 
	"ADRESSIERUNG" VARCHAR2(1 BYTE), 
	"LEISTUNGSBEGINN" DATE, 
	"LEISTUNGSENDE" DATE, 
	"KEY_BEZUG" NUMBER(12,0), 
	"MITGLIED_KZ" VARCHAR2(1 BYTE), 
	"STATUS_GRUND_KENNZ" VARCHAR2(5 BYTE), 
	"BESTELL_GRUND" VARCHAR2(120 BYTE), 
	"PREISGRUPPE" NUMBER(2,0), 
	"WAEHRUNG_KENNZ" VARCHAR2(5 BYTE), 
	"STEUER_HALB" NUMBER(12,6), 
	"STEUER_VOLL" NUMBER(12,6), 
	"KEY_DEPUTAT" NUMBER(10,0), 
	"KENNUNG" VARCHAR2(15 BYTE), 
	"PREIS_GRUND" VARCHAR2(15 BYTE), 
	"AUSWEIS" VARCHAR2(1 BYTE), 
	"BESCHEINIGUNG" VARCHAR2(1 BYTE), 
	"HANDBUCH" VARCHAR2(1 BYTE), 
	"KURS" NUMBER(15,10), 
	"WERBE_KENNZ" VARCHAR2(15 BYTE), 
	"SELEKTIV_RATEN" NUMBER(2,0), 
	"KUENDIGUNG_AM" DATE, 
	"VARIANTE_KENNZ" VARCHAR2(6 BYTE), 
	"IN_DATUM" DATE, 
	"IN_USER" VARCHAR2(15 BYTE), 
	"VIA_BANK_LFDNR" NUMBER(4,0), 
	"ANMELDEDATUM" DATE, 
	"RUECKMELDEDATUM" DATE, 
	"ANMELDE_ART" VARCHAR2(5 BYTE), 
	"EINZEL_PREIS" NUMBER(9,2), 
	"RECH_BETRAG_NETTO_HALB" NUMBER(9,2), 
	"RECH_BETRAG_NETTO_VOLL" NUMBER(9,2), 
	"ZAHLER_ANTEIL" NUMBER(3,0), 
	"ZAHLER_LIMIT" NUMBER(9,2), 
	"ZAHLWEG" VARCHAR2(1 BYTE), 
	"MANDANT" VARCHAR2(5 BYTE)
   )
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "MVHS"."QUITTUNG"."VNR" IS 'Veranstaltungsnummer';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."SEMESTER" IS 'Semester';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."TNR" IS 'Teilnehmernummer';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."STATUS" IS 'Anmeldestatus Teilnehmer';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."ERMAESS" IS 'Ermäßigungskennzeichen';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."GESAMTK" IS 'Wert der Auftragsposition in Brutto- oder Nettopreisen';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."ZAHLWEISE" IS 'Kennzeichen Zahlweise(Scheck,Barzahlung,Überweisung etc) ';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."BEZAHLT" IS 'verbuchter Zahlungseingang bzw. OP-Ausgleich per Fibu-Übergabe';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."KENNZ" IS 'Unterscheidungsmerkmal: Auftragsposition (H,V) bzw. Faktura-/Buchungsposition (A)';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."SYSDATUM" IS 'Systemdatum zum Zeitpunkt der Anmeldung';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."RECHNR" IS 'Rechnungsnummer';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."SOLLSATZ" IS 'Abwicklungsstatus der Fakturaposition (N=neu,T=im Transfer/Rechnung gedruckt,Y=erledigt/an Fibu übergeben';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."VSTATUS" IS 'Veranstaltungsstatus';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."JAHR" IS 'Veranstaltungsjahr';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."KEY_VNR" IS 'Schlüssel zur Veranstaltungsnummer';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."FIRMA_NR" IS 'Firmennummer';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."BEMERKUNG" IS 'selbstklärend';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."PARTNER" IS 'Kennzeichnung Partner->Teilnehmer j/n';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."BERECHNUNGSGRENZE" IS 'die Fälligkeiten dieser Faktura sind alle durch die Berechnungsgrenze limitiert';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."FAELLIG_AM" IS 'Rechnung wir fällig am';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."RATENBEGINN" IS 'selbstklärend';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."RATENENDE" IS 'selbstklärend';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."RECH_DATUM" IS 'Rechnungsdatum';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."RECH_BETRAG" IS 'Rechnungsbetrag';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."MAHN_NR" IS 'Mahnungsnummer';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."PARTNER_TNR" IS 'Partner-Teilnehmernummer';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."ABZUEGL" IS 'Zahlungsrückstand/Überzahlung zur Zeit dieses Faktura-Eintrags';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."RATE" IS 'Anzahl Raten';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."KEY_VTAGE" IS 'Schlüssel zu Veranstaltungstage';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."KEY_QUITTUNG" IS 'Primärschlüssel';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."AUFTRAG_NR" IS 'Auftragsnummer bei Anmeldung';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."MENGE" IS 'Menge dieser Auftragsposition';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."ZAHL_PFLICHTIG" IS 'Debitorennummer ';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."WER_ZAHLT" IS 'Kennzeichen Zahler T-Teilnehmer, F-Firma';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."WER_ANSPRECHPARTNER" IS 'Kennzeichen Ansprechpartner T-Teilnehmer, F-Firma';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."WER_ENTSENDET" IS 'Kennzeichen Entsender ';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."ADRESSIERUNG" IS 'Adressierungskennzeichen';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."LEISTUNGSBEGINN" IS 'selbstklärend';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."LEISTUNGSENDE" IS 'selbstklärend';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."KEY_BEZUG" IS 'Identifikation der Auftragsposition (mit allen zugehörigen Faktura-/Buchungspositionen';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."MITGLIED_KZ" IS 'Kennzeichnung ob Mitglied j/n';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."STATUS_GRUND_KENNZ" IS 'Statusgrund-Erläuterung Teilnehmer->Anmeldung(storniert,wartend,etc.)';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."BESTELL_GRUND" IS 'Begleitender Text zur Anmeldung';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."PREISGRUPPE" IS 'Preisgruppenzuordnung';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."WAEHRUNG_KENNZ" IS 'Währungskennzeichen';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."STEUER_HALB" IS 'Steuerbetrag Halbe MWST';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."STEUER_VOLL" IS 'Steuerbetrag Volle MWST';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."KEY_DEPUTAT" IS 'Schlüssel zu Deputat';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."KENNUNG" IS 'freies Kennzeichen der Auftragsposition, z.B. für manuelle Vergabe von Positionsnummern';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."PREIS_GRUND" IS 'Begründung für den Preis der Auftragsposition';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."AUSWEIS" IS 'Ausweis drucken j/n';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."BESCHEINIGUNG" IS 'Bescheinigung drucken j/n';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."HANDBUCH" IS 'Gutschein Handbuch drucken j/n';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."KURS" IS 'Kursfaktor gegen die Standardwährung';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."WERBE_KENNZ" IS 'Auftrag ist aufgrund dieser Werbemassnahme entstanden';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."SELEKTIV_RATEN" IS 'Verknüpfung der Auftragsposition mit einem Abo-Zahl-Plan (jährliche-monatliche Zahlung), fällig im angegebenen Monat der Abo-Periode';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."KUENDIGUNG_AM" IS 'Auftragsposition wurde gekündigt am';
 
   COMMENT ON COLUMN "MVHS"."QUITTUNG"."VARIANTE_KENNZ" IS 'Auftragsposition wird in der gegebenen Variante ausgeführt ->V_Variante legt die zulässigen Varianten fest';
 
   COMMENT ON TABLE "MVHS"."QUITTUNG"  IS 'Anmeldungen und Rechnungsrelevante Daten';
 

  CREATE INDEX "MVHS"."I11_QUITTUNG" ON "MVHS"."QUITTUNG" ("SOLLSATZ", "RECHNR", "RECH_BETRAG", "ZAHLWEISE", "ABZUEGL", "ZAHL_PFLICHTIG", "WER_ZAHLT", "AUFTRAG_NR") 
  TABLESPACE "USERS" ;
 
  CREATE INDEX "MVHS"."I12_QUITTUNG" ON "MVHS"."QUITTUNG" ("KEY_QUITTUNG", "KEY_VNR", "TNR", "FIRMA_NR", "KENNZ", "STATUS", "WAEHRUNG_KENNZ", "SOLLSATZ", "ZAHLWEISE", "RECHNR", "MENGE", "PREISGRUPPE", "KURS", "BEZAHLT", "GESAMTK", "KENNUNG", "ADRESSIERUNG", "ANMELDEDATUM", "USR_DATUM", "IN_DATUM", "KEY_BEZUG") 
  TABLESPACE "USERS" ;
 
  CREATE INDEX "MVHS"."I13_QUITTUNG" ON "MVHS"."QUITTUNG" ("LEISTUNGSBEGINN", "LEISTUNGSENDE", "KENNZ", "KEY_VTAGE", "KEY_DEPUTAT") 
  TABLESPACE "USERS" ;
 
  CREATE INDEX "MVHS"."I14_QUITTUNG" ON "MVHS"."QUITTUNG" ("KEY_VTAGE", "KEY_DEPUTAT") 
  TABLESPACE "USERS" ;
 
  CREATE INDEX "MVHS"."I15_QUITTUNG" ON "MVHS"."QUITTUNG" ("WERBE_KENNZ") 
  TABLESPACE "USERS" ;
 
  CREATE INDEX "MVHS"."I16_QUITTUNG" ON "MVHS"."QUITTUNG" ("FIRMA_NR", "KENNZ", "STATUS", "GESAMTK") 
  TABLESPACE "USERS" ;
 
  CREATE INDEX "MVHS"."I17_QUITTUNG" ON "MVHS"."QUITTUNG" ("TNR", "JAHR", "SEMESTER", "VNR", "VSTATUS", "KEY_VNR", "KENNZ", "STATUS", "WAEHRUNG_KENNZ", "MENGE", "PREISGRUPPE", "ZAHLWEISE", "ERMAESS", "AUFTRAG_NR", "BEZAHLT", "GESAMTK", "KURS", "MITGLIED_KZ", "KEY_QUITTUNG") 
  TABLESPACE "USERS" ;
 
  CREATE INDEX "MVHS"."I1_QUITTUNG" ON "MVHS"."QUITTUNG" ("KEY_VNR", "KEY_QUITTUNG", "KEY_BEZUG", "ZAHLWEISE", "TNR", "KENNZ", "STATUS", "WAEHRUNG_KENNZ", "GESAMTK", "RECH_BETRAG", "RECHNR", "BEZAHLT", "FAELLIG_AM", "KURS", "ZAHL_PFLICHTIG", "MAHNDATUM_1", "SYSDATUM") 
  TABLESPACE "USERS" ;
 
  CREATE INDEX "MVHS"."I20_QUITTUNG" ON "MVHS"."QUITTUNG" ("IN_USER", "ANMELDEDATUM") 
  TABLESPACE "USERS" ;
 
  CREATE INDEX "MVHS"."I21_QUITTUNG" ON "MVHS"."QUITTUNG" ("ANMELDEDATUM", "KEY_QUITTUNG", "KEY_BEZUG") 
  TABLESPACE "USERS" ;
 
  CREATE INDEX "MVHS"."I22_QUITTUNG" ON "MVHS"."QUITTUNG" ("IN_DATUM", "KEY_QUITTUNG", "KEY_BEZUG") 
  TABLESPACE "USERS" ;
 
  CREATE INDEX "MVHS"."I3_QUITTUNG" ON "MVHS"."QUITTUNG" ("RECHNR", "ZAHLWEG", "MANDANT", "SOLLSATZ") 
  TABLESPACE "USERS" ;
 
  CREATE INDEX "MVHS"."I4_QUITTUNG" ON "MVHS"."QUITTUNG" ("MAHN_NR", "KENNZ", "MAHNDATUM_1", "MAHNDATUM_2", "MAHNDATUM_3", "MAHNDATUM_4") 
  TABLESPACE "USERS" ;
 
  CREATE INDEX "MVHS"."I5_QUITTUNG" ON "MVHS"."QUITTUNG" ("USR_DATUM", "USR_ID", "TTY") 
  TABLESPACE "USERS" ;
 
  CREATE INDEX "MVHS"."I7_QUITTUNG" ON "MVHS"."QUITTUNG" ("AUFTRAG_NR", "TNR", "ZAHL_PFLICHTIG", "KENNZ", "STATUS", "WAEHRUNG_KENNZ", "GESAMTK") 
  TABLESPACE "USERS" ;
 
  CREATE INDEX "MVHS"."I8_QUITTUNG" ON "MVHS"."QUITTUNG" ("KEY_BEZUG", "RECHNR", "ZAHL_PFLICHTIG", "RECH_BETRAG", "BEZAHLT", "ABZUEGL", "GESAMTK", "STATUS", "ZAHLWEISE", "SOLLSATZ", "KENNZ", "WAEHRUNG_KENNZ", "TNR", "KEY_VNR", "KEY_QUITTUNG") 
  TABLESPACE "USERS" ;
 
  CREATE INDEX "MVHS"."I9_QUITTUNG" ON "MVHS"."QUITTUNG" ("ZAHL_PFLICHTIG", "AUFTRAG_NR", "KEY_VNR", "KEY_BEZUG", "KENNZ", "STATUS", "WAEHRUNG_KENNZ", "ZAHLWEISE", "VIA_BANK_LFDNR", "RECHNR", "BEZAHLT", "KURS", "LEISTUNGSENDE") 
  TABLESPACE "USERS" ;
 
  CREATE INDEX "MVHS"."QP" ON "MVHS"."QUITTUNG" ("PARTNER_TNR", "KENNZ", "KEY_VNR", "JAHR", "SEMESTER", "VNR", "STATUS", "ZAHLWEISE", "ERMAESS", "LEISTUNGSBEGINN", "GESAMTK") 
  TABLESPACE "USERS" ;
 
  CREATE INDEX "MVHS"."QUITTUNG1" ON "MVHS"."QUITTUNG" ("JAHR", "SEMESTER", "VNR", "KENNUNG", "KENNZ", "KEY_VNR") 
  TABLESPACE "USERS" ;
 







DROP TABLE "MVHS"."T" ;

CREATE TABLE "MVHS"."T" 
   (	"TNR" NUMBER(8,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(30 BYTE), 
	"VORNAME" VARCHAR2(30 BYTE), 
	"STRASSE" VARCHAR2(35 BYTE), 
	"PLZ" NUMBER(4,0), 
	"ORT" VARCHAR2(50 BYTE), 
	"GEBORT" VARCHAR2(50 BYTE), 
	"GEBDATUM" DATE, 
	"TELDIENSTL" VARCHAR2(35 BYTE), 
	"BERUF" VARCHAR2(40 BYTE), 
	"GESCHLECHT" VARCHAR2(1 BYTE), 
	"ALTERSKLASSE" NUMBER(1,0), 
	"BANK" VARCHAR2(35 BYTE), 
	"BLZ" NUMBER(8,0), 
	"KTONR" VARCHAR2(15 BYTE), 
	"BEMERKUNG" VARCHAR2(200 BYTE), 
	"TITEL" VARCHAR2(20 BYTE), 
	"KONTOINHABER" VARCHAR2(65 BYTE), 
	"KONTOINHABER2" VARCHAR2(65 BYTE), 
	"FIRMA_NR" NUMBER(8,0), 
	"ANFIRMA" VARCHAR2(1 BYTE), 
	"INFOVERSAND" VARCHAR2(1 BYTE), 
	"STAMMKARTE_ERWUENSCHT" VARCHAR2(1 BYTE), 
	"TELEFAX_NR" VARCHAR2(35 BYTE), 
	"KIND1_NAME" VARCHAR2(25 BYTE), 
	"KIND1_GEB_DATUM" DATE, 
	"KIND2_NAME" VARCHAR2(25 BYTE), 
	"KIND2_GEB_DATUM" DATE, 
	"KIND3_NAME" VARCHAR2(25 BYTE), 
	"KIND3_GEB_DATUM" DATE, 
	"TELEFON_PRIVAT" VARCHAR2(35 BYTE), 
	"JAHRGANG" NUMBER(2,0), 
	"KRANKENKASSEN_KUERZEL" VARCHAR2(7 BYTE), 
	"USR_ID" VARCHAR2(30 BYTE), 
	"USR_DATUM" DATE, 
	"AENDERUNG" VARCHAR2(1 BYTE), 
	"BERUF_KZ" VARCHAR2(15 BYTE), 
	"HOBBY_KZ" VARCHAR2(15 BYTE), 
	"PARTNER_TNR" NUMBER(8,0), 
	"POST_AN_PARTNER" VARCHAR2(1 BYTE), 
	"PLZNEU" VARCHAR2(12 BYTE), 
	"LAND_KZ" VARCHAR2(3 BYTE), 
	"ELTERN_TNR" NUMBER(8,0), 
	"KIND" VARCHAR2(1 BYTE), 
	"EINZUG" VARCHAR2(1 BYTE), 
	"POST_AN_ELTERN" VARCHAR2(1 BYTE), 
	"ERMAESS" VARCHAR2(1 BYTE), 
	"MITGLIED_KZ" VARCHAR2(1 BYTE), 
	"ANREDE" VARCHAR2(50 BYTE), 
	"GEBLAND" VARCHAR2(70 BYTE), 
	"DOZNR" NUMBER(8,0), 
	"AKTIV" VARCHAR2(1 BYTE), 
	"BESCHAEFTIGT_SEIT" DATE, 
	"BESCHAEFTIGT_BIS" DATE, 
	"PRUEFER" VARCHAR2(1 BYTE), 
	"PRUEFER_SEIT" DATE, 
	"PRUEFER_BIS" DATE, 
	"VORWAHL" VARCHAR2(10 BYTE), 
	"BUERO_ANREDE" VARCHAR2(35 BYTE), 
	"BUERO_NAME" VARCHAR2(40 BYTE), 
	"ADELSTITEL" VARCHAR2(30 BYTE), 
	"E_MAIL" VARCHAR2(60 BYTE), 
	"TELEFAX" VARCHAR2(35 BYTE), 
	"FOFO_DATUM" DATE, 
	"SPRACH_KENNZ" VARCHAR2(5 BYTE), 
	"ANREDE_CODE" VARCHAR2(1 BYTE), 
	"TITEL_CODE" VARCHAR2(3 BYTE), 
	"ANREDE_ZUSATZ1" VARCHAR2(30 BYTE), 
	"ANREDE_ZUSATZ2" VARCHAR2(30 BYTE), 
	"BUNDESSTAAT" VARCHAR2(5 BYTE), 
	"POSTFACH" VARCHAR2(35 BYTE), 
	"PLZPOST" VARCHAR2(12 BYTE), 
	"PLZORT" VARCHAR2(30 BYTE), 
	"GEHOERT_ZU" VARCHAR2(10 BYTE), 
	"ABTEILUNG" VARCHAR2(50 BYTE), 
	"PREISGRUPPE" NUMBER(2,0), 
	"BRIEFANREDE" VARCHAR2(50 BYTE), 
	"DEBITOR_NR" NUMBER(8,0), 
	"AKTIV_GRUND" VARCHAR2(60 BYTE), 
	"WERBESTOP" VARCHAR2(1 BYTE), 
	"TELEFON_MOBIL" VARCHAR2(35 BYTE), 
	"IN_DATUM" DATE, 
	"LIEFERANT_NR" VARCHAR2(20 BYTE), 
	"ABTEILUNG_KENNZ" VARCHAR2(15 BYTE), 
	"ANMELDE_STOP" VARCHAR2(1 BYTE), 
	"E_MAIL_PRIVAT" VARCHAR2(60 BYTE), 
	"KST_KENNZ" VARCHAR2(12 BYTE), 
	"MOBIL_PRIVAT" VARCHAR2(35 BYTE), 
	"TEAM_KENNZ" VARCHAR2(15 BYTE), 
	"TELEFON_BEMERKUNG" VARCHAR2(2000 BYTE), 
	"FIBU_AM" DATE, 
	"IN_USER" VARCHAR2(15 BYTE), 
	"TITEL_RECHTS" VARCHAR2(20 BYTE), 
	"INTERNET_DIENSTL" VARCHAR2(60 BYTE), 
	"INTERNET_PRIVAT" VARCHAR2(60 BYTE), 
	"BERUF_KATEGORIE" VARCHAR2(5 BYTE), 
	"KOMM_PRAEFERENZ" VARCHAR2(1 BYTE), 
	"SCHULABSCHLUSS" VARCHAR2(5 BYTE), 
	"STAATSANGEHOERIG" VARCHAR2(3 BYTE), 
	"ERMAESS_BIS" DATE, 
	"KRANKEN_VRS" VARCHAR2(1 BYTE), 
	"RENTEN_VRS" VARCHAR2(1 BYTE), 
	"KUENSTLER_ABGABE" VARCHAR2(1 BYTE), 
	"LOHNSTEUER" VARCHAR2(1 BYTE), 
	"GERING_VERDIENER" VARCHAR2(1 BYTE), 
	"FIBU_STATUS" VARCHAR2(1 BYTE), 
	"FIBU_LAUFNR" NUMBER(12,0), 
	"ADRESS_ZUSATZ" VARCHAR2(50 BYTE)
   ) 
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "MVHS"."T"."TNR" IS 'Teilnehmernummer';
 
   COMMENT ON COLUMN "MVHS"."T"."NAME" IS 'Name';
 
   COMMENT ON COLUMN "MVHS"."T"."VORNAME" IS 'Vorname';
 
   COMMENT ON COLUMN "MVHS"."T"."STRASSE" IS 'Strasse';
 
   COMMENT ON COLUMN "MVHS"."T"."ORT" IS 'Ort';
 
   COMMENT ON COLUMN "MVHS"."T"."GEBORT" IS 'Geburtsort';
 
   COMMENT ON COLUMN "MVHS"."T"."GEBDATUM" IS 'Geburtsdatum';
 
   COMMENT ON COLUMN "MVHS"."T"."TELDIENSTL" IS 'Dienstlich telefonisch erreichbar';
 
   COMMENT ON COLUMN "MVHS"."T"."BERUF" IS 'Zuordnung Teilnehmer -> Beruf';
 
   COMMENT ON COLUMN "MVHS"."T"."GESCHLECHT" IS 'selbstklärend';
 
   COMMENT ON COLUMN "MVHS"."T"."BANK" IS 'Zuordnung Teilnehmer -> Bank';
 
   COMMENT ON COLUMN "MVHS"."T"."BLZ" IS 'Bankleitzahl des Teilnehmers';
 
   COMMENT ON COLUMN "MVHS"."T"."KTONR" IS 'Kontonummer des Teilnehmers/Dozenten';
 
   COMMENT ON COLUMN "MVHS"."T"."BEMERKUNG" IS 'Interne Bemerkung zur Person';
 
   COMMENT ON COLUMN "MVHS"."T"."TITEL" IS 'selbstklärend';
 
   COMMENT ON COLUMN "MVHS"."T"."KONTOINHABER" IS 'selbstklärend';
 
   COMMENT ON COLUMN "MVHS"."T"."KONTOINHABER2" IS 'selbstklärend';
 
   COMMENT ON COLUMN "MVHS"."T"."FIRMA_NR" IS 'Zuordnung Teilnehmer/Dozent -> Firma';
 
   COMMENT ON COLUMN "MVHS"."T"."ANFIRMA" IS 'Post an Firma';
 
   COMMENT ON COLUMN "MVHS"."T"."TELEFAX_NR" IS 'private Telefaxnummer';
 
   COMMENT ON COLUMN "MVHS"."T"."TELEFON_PRIVAT" IS 'Privat telefonisch erreichbar';
 
   COMMENT ON COLUMN "MVHS"."T"."KRANKENKASSEN_KUERZEL" IS 'Kennzeichen Krankenkassen-Zugehörigkeit';
 
   COMMENT ON COLUMN "MVHS"."T"."USR_ID" IS 'Wer hat erfasst?';
 
   COMMENT ON COLUMN "MVHS"."T"."USR_DATUM" IS 'Datum Erfassung';
 
   COMMENT ON COLUMN "MVHS"."T"."BERUF_KZ" IS 'Kennzeichen Beruf';
 
   COMMENT ON COLUMN "MVHS"."T"."HOBBY_KZ" IS 'Zuordnung Teilnehmer -> Hobby';
 
   COMMENT ON COLUMN "MVHS"."T"."PARTNER_TNR" IS 'Teilnehmernummer des Partners';
 
   COMMENT ON COLUMN "MVHS"."T"."PLZNEU" IS 'Postleitzahl(neu)';
 
   COMMENT ON COLUMN "MVHS"."T"."LAND_KZ" IS 'Länderkennzeichen';
 
   COMMENT ON COLUMN "MVHS"."T"."ELTERN_TNR" IS 'Teilnehmernummer des Partners';
 
   COMMENT ON COLUMN "MVHS"."T"."KIND" IS 'Klassifikation Kind (j/n)';
 
   COMMENT ON COLUMN "MVHS"."T"."EINZUG" IS 'Bankeinzug gesperrt (j/n)';
 
   COMMENT ON COLUMN "MVHS"."T"."ERMAESS" IS 'Ermässigungskennzeichen';
 
   COMMENT ON COLUMN "MVHS"."T"."MITGLIED_KZ" IS 'Kennzeichen Mitglied j/n';
 
   COMMENT ON COLUMN "MVHS"."T"."ANREDE" IS 'Anredezusatz';
 
   COMMENT ON COLUMN "MVHS"."T"."GEBLAND" IS 'Geburtsland';
 
   COMMENT ON COLUMN "MVHS"."T"."DOZNR" IS 'Dozentennummer';
 
   COMMENT ON COLUMN "MVHS"."T"."AKTIV" IS 'Kennzeichnung Aktivstatus j/n';
 
   COMMENT ON COLUMN "MVHS"."T"."BESCHAEFTIGT_SEIT" IS 'Wenn Teilnehmer=Dozent';
 
   COMMENT ON COLUMN "MVHS"."T"."BESCHAEFTIGT_BIS" IS 'Wenn Teilnehmer=Dozent';
 
   COMMENT ON COLUMN "MVHS"."T"."PRUEFER" IS 'Kennzeichnung des Dozenten ob Prüfer j/n';
 
   COMMENT ON COLUMN "MVHS"."T"."PRUEFER_SEIT" IS 'selbstklärend';
 
   COMMENT ON COLUMN "MVHS"."T"."PRUEFER_BIS" IS 'selbstklärend';
 
   COMMENT ON COLUMN "MVHS"."T"."ADELSTITEL" IS 'selbstklärend';
 
   COMMENT ON COLUMN "MVHS"."T"."E_MAIL" IS 'E-Mail-Adresse';
 
   COMMENT ON COLUMN "MVHS"."T"."TELEFAX" IS 'geschäftliche Telefaxnummer';
 
   COMMENT ON COLUMN "MVHS"."T"."SPRACH_KENNZ" IS 'Sprachkennzeichen';
 
   COMMENT ON COLUMN "MVHS"."T"."ANREDE_CODE" IS 'Kennzeichen Anrede-Codes';
 
   COMMENT ON COLUMN "MVHS"."T"."TITEL_CODE" IS 'Titel-Codes ->Stamm';
 
   COMMENT ON COLUMN "MVHS"."T"."BUNDESSTAAT" IS 'Zuordnung Stadt zu Bundesstaat';
 
   COMMENT ON COLUMN "MVHS"."T"."POSTFACH" IS 'Postfach';
 
   COMMENT ON COLUMN "MVHS"."T"."GEHOERT_ZU" IS 'Zuordnung Zugehörigkeit(Abteilung)';
 
   COMMENT ON COLUMN "MVHS"."T"."ABTEILUNG" IS 'Zuordnung Teilnehmer -> Abteilung';
 
   COMMENT ON COLUMN "MVHS"."T"."PREISGRUPPE" IS 'Preisgruppenzuordnung 1-30';
 
   COMMENT ON COLUMN "MVHS"."T"."BRIEFANREDE" IS 'Individuelle Anredeform am Briefbeginn';
 
   COMMENT ON COLUMN "MVHS"."T"."DEBITOR_NR" IS 'Debitorennummer in der Finanzbuchhaltung';
 
   COMMENT ON COLUMN "MVHS"."T"."AKTIV_GRUND" IS 'Begründung Aktivstatus';
 
   COMMENT ON COLUMN "MVHS"."T"."WERBESTOP" IS 'Anweisung für die Werbung: Werbestop (j/n)';
 
   COMMENT ON COLUMN "MVHS"."T"."TELEFON_MOBIL" IS 'geschäftliche Mobil-Telefonnummer';
 
   COMMENT ON COLUMN "MVHS"."T"."ANMELDE_STOP" IS 'Hinweis für die Anmeldung: es gilt Anmeldestop (j/n)';
 
   COMMENT ON TABLE "MVHS"."T"  IS 'Teilnehmerstamm';
 

  CREATE INDEX "MVHS"."INDEX3" ON "MVHS"."T" ("NAME") 
  TABLESPACE "USERS" ;
 
  CREATE INDEX "MVHS"."INDEX4" ON "MVHS"."T" ("VORNAME") 
  TABLESPACE "USERS" ;
 
  CREATE INDEX "MVHS"."NAME" ON "MVHS"."T" ("NAME", "VORNAME", "GESCHLECHT", "STRASSE", "PLZNEU", "ORT", "GEBORT", "GEBLAND", "GEBDATUM", "BERUF", "TITEL", "FIRMA_NR", "TNR") 
  TABLESPACE "USERS" ;
 
  CREATE INDEX "MVHS"."TFIRMA" ON "MVHS"."T" ("FIRMA_NR") 
  TABLESPACE "USERS" ;
 
  CREATE INDEX "MVHS"."TNR" ON "MVHS"."T" ("TNR", "NAME", "VORNAME", "ORT", "GESCHLECHT", "GEBDATUM", "BERUF_KZ", "HOBBY_KZ", "ANMELDE_STOP", "WERBESTOP", "ERMAESS", "ERMAESS_BIS") 
  TABLESPACE "USERS" ;
 
  CREATE INDEX "MVHS"."TNRFIRMA" ON "MVHS"."T" ("TNR", "FIRMA_NR", "ANFIRMA") 
  TABLESPACE "USERS" ;
 
  CREATE INDEX "MVHS"."T_DOZ" ON "MVHS"."T" ("TNR", "PRUEFER", "AKTIV") 
  TABLESPACE "USERS" ;
 
  CREATE INDEX "MVHS"."T_DOZ2" ON "MVHS"."T" ("AKTIV", "PRUEFER", "TNR") 
  TABLESPACE "USERS" ;
 
  CREATE INDEX "MVHS"."T_FIBU" ON "MVHS"."T" ("FIBU_STATUS", "FIBU_LAUFNR") 
  TABLESPACE "USERS" ;
 
  CREATE INDEX "MVHS"."T_PLZNEU" ON "MVHS"."T" ("PLZNEU", "TNR") 
  TABLESPACE "USERS" ;
 










DROP TABLE "MVHS"."V" ;
CREATE TABLE "MVHS"."V" 
   (	"VNR" VARCHAR2(12 BYTE) NOT NULL ENABLE, 
	"SEMESTER" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"STADTBEZ" NUMBER(2,0), 
	"UTEXT1" VARCHAR2(40 BYTE), 
	"UTEXT2" VARCHAR2(40 BYTE), 
	"UEFACHBER1" NUMBER(7,2), 
	"BEGDATUM" DATE, 
	"ENDDATUM" DATE, 
	"DAUER" VARCHAR2(18 BYTE), 
	"MINT" NUMBER(4,0), 
	"MAXT" NUMBER(4,0), 
	"FORMNR" VARCHAR2(2 BYTE), 
	"PARTNERNR" NUMBER(8,0), 
	"FOERDERNR" NUMBER(8,0), 
	"KURSTYP" VARCHAR2(2 BYTE), 
	"ADRESSATENGR" NUMBER(2,0), 
	"EINNAHME" NUMBER(8,2), 
	"KOSTEN1" NUMBER(8,2), 
	"ZUSATZK" NUMBER(8,2), 
	"TEXTZUSATZK" VARCHAR2(40 BYTE), 
	"ZENTRALEINSCHR" VARCHAR2(1 BYTE), 
	"AENDERUNGSDATUM" DATE, 
	"BEMERKUNG" VARCHAR2(2000 BYTE), 
	"STATUS" VARCHAR2(1 BYTE), 
	"JAHR" VARCHAR2(2 BYTE) NOT NULL ENABLE, 
	"ABSCHNITT" VARCHAR2(1 BYTE), 
	"WARTELISTE" VARCHAR2(1 BYTE), 
	"KEINE_ERMAESS_FUER" VARCHAR2(60 BYTE), 
	"TEXTNR" VARCHAR2(5 BYTE), 
	"KEY_VNR" NUMBER(8,0), 
	"USR_ID" VARCHAR2(30 BYTE), 
	"USR_DATUM" DATE, 
	"VTAGE_START" DATE, 
	"WARTEND" NUMBER(3,0), 
	"STORNIERT" NUMBER(3,0), 
	"BELEGT" NUMBER(8,0), 
	"HAUPTDOZNR" NUMBER(8,0), 
	"MAL" NUMBER(3,0), 
	"ORTNR" VARCHAR2(5 BYTE), 
	"RAUM" VARCHAR2(5 BYTE), 
	"ZEIT" VARCHAR2(30 BYTE), 
	"RATEN" VARCHAR2(1 BYTE), 
	"EINZELPLATZ" VARCHAR2(1 BYTE), 
	"ALTERNATIVEN" VARCHAR2(1 BYTE), 
	"BELEGT_WEIBLICH" NUMBER(8,0), 
	"KOSTEN_LAST" NUMBER(8,2), 
	"ZUSATZK_LAST" NUMBER(8,2), 
	"TEXTZUSATZK_LAST" VARCHAR2(40 BYTE), 
	"LEISTUNGSART" VARCHAR2(5 BYTE), 
	"LEISTUNGSGRUPPE" VARCHAR2(5 BYTE), 
	"WOCHENTAG" VARCHAR2(3 BYTE), 
	"TAGESZEIT" VARCHAR2(3 BYTE), 
	"VERMITTLUNGSART" VARCHAR2(3 BYTE), 
	"VERFUEGBAR" NUMBER(10,2), 
	"KEY_ORT" NUMBER(8,0), 
	"KEY_RAUM" NUMBER(10,0), 
	"KEY_TEXT" NUMBER(8,0), 
	"KOSTEN3" NUMBER(8,2), 
	"EK_ZULETZT" NUMBER(8,2), 
	"PLANT" NUMBER(4,0), 
	"ZIELGRUPPE" VARCHAR2(5 BYTE), 
	"STANDORT" VARCHAR2(5 BYTE), 
	"FACH_REFERENT" VARCHAR2(15 BYTE), 
	"PLANENDER_REFERENT" VARCHAR2(15 BYTE), 
	"DURCHFUEHRENDER_REFERENT" VARCHAR2(15 BYTE), 
	"THEMA_HAUPTBEREICH" VARCHAR2(5 BYTE), 
	"THEMA_BEREICH" VARCHAR2(5 BYTE), 
	"THEMA_TEILBEREICH" VARCHAR2(5 BYTE), 
	"VERRECHNUNG_KENNZ" VARCHAR2(5 BYTE), 
	"VERRECHNUNG_BEMERKUNG" VARCHAR2(100 BYTE), 
	"WUNSCH_AKADEMIE" VARCHAR2(5 BYTE), 
	"WUNSCH_GRUENDE" VARCHAR2(100 BYTE), 
	"WUNSCHTERMIN" VARCHAR2(50 BYTE), 
	"WUNSCHTERMIN_GRUENDE" VARCHAR2(100 BYTE), 
	"TERMIN_AUSSCHLUSS" VARCHAR2(50 BYTE), 
	"TERMIN_AUSSCHLUSS_GRUENDE" VARCHAR2(100 BYTE), 
	"TERMIN_INFOBLATT" DATE, 
	"MERKER_INFOBLATT" VARCHAR2(1 BYTE), 
	"TERMIN_TAGUNGSPROGRAMM" DATE, 
	"MERKER_TAGUNGSPROGRAMM" VARCHAR2(1 BYTE), 
	"TERMIN_KATALOG" DATE, 
	"MERKER_KATALOG" VARCHAR2(1 BYTE), 
	"UTEXT" VARCHAR2(200 BYTE), 
	"KOSTEN4" NUMBER(8,2), 
	"KOSTEN5" NUMBER(8,2), 
	"KOSTEN6" NUMBER(8,2), 
	"KOSTEN7" NUMBER(8,2), 
	"KOSTEN8" NUMBER(8,2), 
	"KOSTEN9" NUMBER(8,2), 
	"KOSTEN10" NUMBER(8,2), 
	"KOSTEN11" NUMBER(8,2), 
	"KOSTEN12" NUMBER(8,2), 
	"KOSTEN13" NUMBER(8,2), 
	"KOSTEN14" NUMBER(8,2), 
	"PLAN_ERLOES" NUMBER(12,2), 
	"KTR_KENNZ" VARCHAR2(12 BYTE), 
	"KST_KENNZ" VARCHAR2(12 BYTE), 
	"KONTO" NUMBER(8,0), 
	"AUSWEIS" VARCHAR2(1 BYTE), 
	"BESCHEINIGUNG" VARCHAR2(1 BYTE), 
	"HANDBUCH" VARCHAR2(1 BYTE), 
	"MAXT_MERKER" VARCHAR2(1 BYTE), 
	"KOSTEN15" NUMBER(8,2), 
	"KOSTEN16" NUMBER(8,2), 
	"KOSTEN17" NUMBER(8,2), 
	"KOSTEN18" NUMBER(8,2), 
	"KOSTEN19" NUMBER(8,2), 
	"KOSTEN20" NUMBER(8,2), 
	"KOSTEN21" NUMBER(8,2), 
	"KOSTEN22" NUMBER(8,2), 
	"KOSTEN23" NUMBER(8,2), 
	"KOSTEN24" NUMBER(8,2), 
	"KOSTEN25" NUMBER(8,2), 
	"KOSTEN26" NUMBER(8,2), 
	"KOSTEN27" NUMBER(8,2), 
	"KOSTEN28" NUMBER(8,2), 
	"KOSTEN29" NUMBER(8,2), 
	"KOSTEN30" NUMBER(8,2), 
	"FAELLIG_AM" DATE, 
	"TXTHANDBUCH" VARCHAR2(120 BYTE), 
	"ZUSATZTEXT" VARCHAR2(2000 BYTE), 
	"HINWEIS" VARCHAR2(2000 BYTE), 
	"PLAN_AKADEMIE" VARCHAR2(5 BYTE), 
	"STAMM_NR" VARCHAR2(12 BYTE), 
	"ZIELTEXT" VARCHAR2(2000 BYTE), 
	"FREMDKLASSIFIKATION" VARCHAR2(30 BYTE), 
	"UNTERTHEMA" VARCHAR2(5 BYTE), 
	"UNTERTITEL" VARCHAR2(2000 BYTE), 
	"FIRMA_NR" NUMBER(8,0), 
	"UTAGE" NUMBER(6,2), 
	"ZEITTAGE" NUMBER(6,2), 
	"VERSION" VARCHAR2(2 BYTE), 
	"VORLAUF_UNTERLAGEN" NUMBER(4,0), 
	"AUSWEIS_TYP" VARCHAR2(1 BYTE), 
	"KAT_TXTVORLAUF" VARCHAR2(2000 BYTE), 
	"KAT_TXTLEITUNG" VARCHAR2(2000 BYTE), 
	"KAT_TXTDOZENTEN" VARCHAR2(2000 BYTE), 
	"KAT_TXTVERBINDUNG" VARCHAR2(2000 BYTE), 
	"KAT_TXTORT" VARCHAR2(2000 BYTE), 
	"KAT_TXTTERMIN" VARCHAR2(2000 BYTE), 
	"KAT_TXTGEBUEHR" VARCHAR2(2000 BYTE), 
	"UNTERTHEMA_A1" VARCHAR2(5 BYTE), 
	"UNTERTHEMA_A2" VARCHAR2(5 BYTE), 
	"UNTERTHEMA_A3" VARCHAR2(5 BYTE), 
	"FACH_NOTIZ" VARCHAR2(2000 BYTE), 
	"DURCHFUEHRENDER_NOTIZ" VARCHAR2(2000 BYTE), 
	"PLANENDER_NOTIZ" VARCHAR2(2000 BYTE), 
	"TERMIN_WERBUNG" DATE, 
	"MERKER_WERBUNG" VARCHAR2(1 BYTE), 
	"BESTAETIGUNG" VARCHAR2(1 BYTE), 
	"BEARBEITER" VARCHAR2(15 BYTE), 
	"GEZAEHLT" NUMBER(8,0), 
	"IN_DATUM" DATE, 
	"IN_USER" VARCHAR2(15 BYTE), 
	"KAT_TXTERSTATTUNG" VARCHAR2(2000 BYTE), 
	"KAT_TXTINHALT" VARCHAR2(2000 BYTE), 
	"KAT_TXTPROGRAMM" VARCHAR2(2000 BYTE), 
	"TERMIN_MELDESCHLUSS" DATE, 
	"TERMIN_ZUSAGE" DATE, 
	"WIEDERHOLUNG" VARCHAR2(3 BYTE), 
	"ENDZEIT" VARCHAR2(30 BYTE), 
	"MERKER_AUSSCHLUSS" VARCHAR2(1 BYTE), 
	"MERKER_MELDESCHLUSS" VARCHAR2(1 BYTE), 
	"MERKER_ZUSAGE" VARCHAR2(1 BYTE), 
	"VERRECHNUNGSWERT" NUMBER(7,2), 
	"GEZAEHLT_WEIBLICH" NUMBER(8,0), 
	"ANMELDE_HINWEIS_KENNZ" VARCHAR2(5 BYTE), 
	"ANWENDUNG_GEBIET" VARCHAR2(10 BYTE), 
	"LIZENZART" VARCHAR2(10 BYTE), 
	"LIZENZ_GEBIET" VARCHAR2(10 BYTE), 
	"KAT_TXTVORAUSSETZUNG" VARCHAR2(2000 BYTE), 
	"LIZENZ_GRUNDERWERB" VARCHAR2(1 BYTE), 
	"LIZENZ_INTERESSE" VARCHAR2(1 BYTE), 
	"TERMIN_STORNO_VORLEISTUNG" DATE, 
	"ANZAHLUNG_FAELLIG_AM" DATE, 
	"ANZAHLUNG_PROZENT" NUMBER(5,2), 
	"ANZAHLUNG_FAELLIG_TAGE" NUMBER(3,0), 
	"NORMAL_MINT" NUMBER(4,0), 
	"KUERZUNG_MINT" NUMBER(4,0), 
	"KONFIG_KENNZ" VARCHAR2(12 BYTE), 
	"KUNST_GATTUNG" VARCHAR2(5 BYTE), 
	"REFERAT_KENNZ" VARCHAR2(10 BYTE), 
	"VART_BVV" VARCHAR2(4 BYTE), 
	"THEMA_BVV" VARCHAR2(4 BYTE), 
	"VZIEL_BVV" VARCHAR2(4 BYTE), 
	"ZIELGRUPPE_BVV" VARCHAR2(2 BYTE), 
	"KOOPERATION_BVV" VARCHAR2(2 BYTE), 
	"DOPPELSTD_BVV" NUMBER(6,2)
   ) 
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "MVHS"."V"."VNR" IS 'Veranstaltungsnummer';
 
   COMMENT ON COLUMN "MVHS"."V"."SEMESTER" IS 'Planungsperiode Semester';
 
   COMMENT ON COLUMN "MVHS"."V"."UTEXT1" IS 'Veranstaltungsbezeichnung 1';
 
   COMMENT ON COLUMN "MVHS"."V"."UTEXT2" IS 'Veranstaltungsbezeichnung 2';
 
   COMMENT ON COLUMN "MVHS"."V"."BEGDATUM" IS 'Beginndatum der Veranstaltung';
 
   COMMENT ON COLUMN "MVHS"."V"."ENDDATUM" IS 'Letzter Veranstaltungstag';
 
   COMMENT ON COLUMN "MVHS"."V"."DAUER" IS 'Anzahl Unterrichtstage';
 
   COMMENT ON COLUMN "MVHS"."V"."MINT" IS 'Anzahl Minimal-Teilnehmer';
 
   COMMENT ON COLUMN "MVHS"."V"."MAXT" IS 'Anzahl Maximal-Teilnehmer';
 
   COMMENT ON COLUMN "MVHS"."V"."FORMNR" IS 'Kennzeichen Kurstyp(Seminar,Kurs etc.)';
 
   COMMENT ON COLUMN "MVHS"."V"."PARTNERNR" IS 'Zuordnung Veranstaltung ->Partner';
 
   COMMENT ON COLUMN "MVHS"."V"."FOERDERNR" IS 'Förderung der Veranstaltung durch';
 
   COMMENT ON COLUMN "MVHS"."V"."KURSTYP" IS 'Kurszeittyp';
 
   COMMENT ON COLUMN "MVHS"."V"."ADRESSATENGR" IS 'Kennzeichen Adressatengruppe';
 
   COMMENT ON COLUMN "MVHS"."V"."EINNAHME" IS 'Geplante Einnahmen';
 
   COMMENT ON COLUMN "MVHS"."V"."KOSTEN1" IS 'Kosten der Leistung';
 
   COMMENT ON COLUMN "MVHS"."V"."ZENTRALEINSCHR" IS 'Kennzeichnung Zentraleinschreibung';
 
   COMMENT ON COLUMN "MVHS"."V"."BEMERKUNG" IS 'Erläuterung zur Veranstaltung';
 
   COMMENT ON COLUMN "MVHS"."V"."STATUS" IS 'Veranstaltungsstatus';
 
   COMMENT ON COLUMN "MVHS"."V"."JAHR" IS 'Veranstaltungsjahr formatYY';
 
   COMMENT ON COLUMN "MVHS"."V"."WARTELISTE" IS 'Kennzeichnung Anmeldung auf Warteliste';
 
   COMMENT ON COLUMN "MVHS"."V"."KEINE_ERMAESS_FUER" IS 'Kennzeichen Ermässigung ausgeschlossen';
 
   COMMENT ON COLUMN "MVHS"."V"."TEXTNR" IS 'Zuordnung Veranstaltung -> Textbaustein';
 
   COMMENT ON COLUMN "MVHS"."V"."KEY_VNR" IS 'Primärschlüssel parallel zu (jahr,semester,vnr)';
 
   COMMENT ON COLUMN "MVHS"."V"."USR_ID" IS 'Personifizierung bei Anlage Veranstaltung(Wer hat erfasst?)';
 
   COMMENT ON COLUMN "MVHS"."V"."USR_DATUM" IS 'Anlagedatum der Veranstaltung';
 
   COMMENT ON COLUMN "MVHS"."V"."VTAGE_START" IS '1.Veranstaltungstag';
 
   COMMENT ON COLUMN "MVHS"."V"."WARTEND" IS 'Anzahl Wartender Teilnehmer';
 
   COMMENT ON COLUMN "MVHS"."V"."STORNIERT" IS 'Anzahl Stornierte Teilnehmer';
 
   COMMENT ON COLUMN "MVHS"."V"."BELEGT" IS 'Aktuelle Belegung zur Veranstaltung';
 
   COMMENT ON COLUMN "MVHS"."V"."HAUPTDOZNR" IS 'Hauptdozenten-Nummer';
 
   COMMENT ON COLUMN "MVHS"."V"."MAL" IS 'Anzahl Veranstaltungstage';
 
   COMMENT ON COLUMN "MVHS"."V"."ORTNR" IS 'Zuordnung Veranstaltung ->Ort';
 
   COMMENT ON COLUMN "MVHS"."V"."RAUM" IS 'Zuordnung Veranstaltung -> Raum';
 
   COMMENT ON COLUMN "MVHS"."V"."ZEIT" IS 'Kurszeiten';
 
   COMMENT ON COLUMN "MVHS"."V"."ALTERNATIVEN" IS 'Kennzeichen Alternativen vorhanden j/n';
 
   COMMENT ON COLUMN "MVHS"."V"."BELEGT_WEIBLICH" IS 'Aktuelle Belegung(nur weiblich) zur Veranstaltung';
 
   COMMENT ON COLUMN "MVHS"."V"."LEISTUNGSART" IS 'selbstklärend';
 
   COMMENT ON COLUMN "MVHS"."V"."LEISTUNGSGRUPPE" IS 'Leistungsgruppe ->Stamm';
 
   COMMENT ON COLUMN "MVHS"."V"."TAGESZEIT" IS 'selbstklärend';
 
   COMMENT ON COLUMN "MVHS"."V"."VERMITTLUNGSART" IS 'Vermittlungsart ->Stamm';
 
   COMMENT ON COLUMN "MVHS"."V"."VERFUEGBAR" IS 'Freie Plätze zur Veranstaltung';
 
   COMMENT ON COLUMN "MVHS"."V"."KEY_ORT" IS 'Schlüssel Veranstaltung->Ort';
 
   COMMENT ON COLUMN "MVHS"."V"."KEY_RAUM" IS 'Schlüssel Veranstaltung->Raum';
 
   COMMENT ON COLUMN "MVHS"."V"."KEY_TEXT" IS 'Schlüssel Veranstaltung->Texte';
 
   COMMENT ON COLUMN "MVHS"."V"."EK_ZULETZT" IS 'Letzter Einkaufspreis Rel.Kalkulation';
 
   COMMENT ON COLUMN "MVHS"."V"."PLANT" IS 'Geplante Teilnehmer';
 
   COMMENT ON COLUMN "MVHS"."V"."ZIELGRUPPE" IS 'Kennzeichnung Zielgruppe';
 
   COMMENT ON COLUMN "MVHS"."V"."STANDORT" IS 'für diese Leistung zuständige Geschäftseinheit';
 
   COMMENT ON COLUMN "MVHS"."V"."FACH_REFERENT" IS 'Zuordnung Fachreferat in der Planungsphase';
 
   COMMENT ON COLUMN "MVHS"."V"."PLANENDER_REFERENT" IS 'Zuordnung Veranstaltung ->Referent(Planungsphase)';
 
   COMMENT ON COLUMN "MVHS"."V"."WUNSCHTERMIN" IS 'Wunschtermin(Planungsphase)';
 
   COMMENT ON COLUMN "MVHS"."V"."WUNSCHTERMIN_GRUENDE" IS 'Wunschtermin Ausführung(Planungsphase)';
 
   COMMENT ON COLUMN "MVHS"."V"."MERKER_INFOBLATT" IS 'Hilfsfeld';
 
   COMMENT ON COLUMN "MVHS"."V"."MERKER_TAGUNGSPROGRAMM" IS 'Hilfsfeld';
 
   COMMENT ON COLUMN "MVHS"."V"."MERKER_KATALOG" IS 'Hilfsfeld';
 
   COMMENT ON COLUMN "MVHS"."V"."UTEXT" IS 'Veranstaltungsbezeichnung';
 
   COMMENT ON COLUMN "MVHS"."V"."PLAN_ERLOES" IS 'Geplante Erlöse';
 
   COMMENT ON COLUMN "MVHS"."V"."KST_KENNZ" IS 'Kostenstellen-Kennzeichen';
 
   COMMENT ON COLUMN "MVHS"."V"."KONTO" IS 'Konto zum verbuchen der Umsätze mit dieser Leistung';
 
   COMMENT ON COLUMN "MVHS"."V"."AUSWEIS" IS 'Kennzeichen Ausweis drucken';
 
   COMMENT ON COLUMN "MVHS"."V"."BESCHEINIGUNG" IS 'Kennzeichnung Bescheinigung drucken';
 
   COMMENT ON COLUMN "MVHS"."V"."HANDBUCH" IS 'Fixe Zuordnung Lehrmittel';
 
   COMMENT ON COLUMN "MVHS"."V"."FAELLIG_AM" IS 'Abweichendes Fälligkeitsdatum';
 
   COMMENT ON COLUMN "MVHS"."V"."TXTHANDBUCH" IS 'Zuordnung Veranstaltung -> Lehrmittel';
 
   COMMENT ON COLUMN "MVHS"."V"."HINWEIS" IS 'selbstklärend';
 
   COMMENT ON COLUMN "MVHS"."V"."PLAN_AKADEMIE" IS 'Zuordnung Veranstaltung ->Akademie(Planungsphase)';
 
   COMMENT ON COLUMN "MVHS"."V"."ZEITTAGE" IS 'Anzahl Zeittage';
 
   COMMENT ON TABLE "MVHS"."V"  IS 'Veranstaltungen';
 

  CREATE INDEX "MVHS"."I10_V" ON "MVHS"."V" ("KEY_VNR", "BEARBEITER", "DURCHFUEHRENDER_REFERENT", "PLANENDER_REFERENT", "FACH_REFERENT") 
  TABLESPACE "USERS" ;
 
  CREATE INDEX "MVHS"."I11_V" ON "MVHS"."V" ("KEY_VNR", "LEISTUNGSART", "LEISTUNGSGRUPPE", "KURSTYP", "LIZENZART", "FORMNR", "PARTNERNR", "FOERDERNR", "ADRESSATENGR") 
  TABLESPACE "USERS" ;
 
  CREATE INDEX "MVHS"."I15_V" ON "MVHS"."V" ("KEY_RAUM", "KEY_VNR") 
  TABLESPACE "USERS" ;
 
  CREATE INDEX "MVHS"."I1_MVHS_V" ON "MVHS"."V" ("JAHR", "SEMESTER", "REFERAT_KENNZ", "KEY_VNR") 
  TABLESPACE "USERS" ;
 
  CREATE INDEX "MVHS"."I1_V" ON "MVHS"."V" ("KEY_VNR", "SEMESTER", "JAHR", "STATUS", "VNR", "UTEXT1", "UTEXT", "ZIELTEXT", "ZIELGRUPPE", "ANMELDE_HINWEIS_KENNZ", "WIEDERHOLUNG") 
  TABLESPACE "USERS" ;
 
  CREATE INDEX "MVHS"."I2_MVHS_V" ON "MVHS"."V" ("REFERAT_KENNZ") 
  TABLESPACE "USERS" ;
 
  CREATE INDEX "MVHS"."I2_V" ON "MVHS"."V" ("BEGDATUM", "ENDDATUM", "KEY_VNR") 
  TABLESPACE "USERS" ;
 
  CREATE UNIQUE INDEX "MVHS"."I3_MVHS_V" ON "MVHS"."V" ("KEY_VNR", "REFERAT_KENNZ") 
  TABLESPACE "USERS" ;
 
  CREATE INDEX "MVHS"."I3_V" ON "MVHS"."V" ("UTEXT1", "UTEXT", "KEY_VNR") 
  TABLESPACE "USERS" ;
 
  CREATE INDEX "MVHS"."I4_V" ON "MVHS"."V" ("THEMA_HAUPTBEREICH", "THEMA_BEREICH", "THEMA_TEILBEREICH", "UNTERTHEMA", "KEY_VNR") 
  TABLESPACE "USERS" ;
 
  CREATE INDEX "MVHS"."I5_V" ON "MVHS"."V" ("UNTERTHEMA", "STAMM_NR", "VERSION", "KEY_VNR") 
  TABLESPACE "USERS" ;
 
  CREATE INDEX "MVHS"."I6_V" ON "MVHS"."V" ("LEISTUNGSART", "KEY_VNR") 
  TABLESPACE "USERS" ;
 
  CREATE INDEX "MVHS"."I7_V" ON "MVHS"."V" ("KEY_VNR", "BEGDATUM", "ENDDATUM", "MAXT", "MINT", "PLANT", "ZEIT", "ENDZEIT", "MAL", "UEFACHBER1", "HAUPTDOZNR", "ORTNR", "STANDORT", "RAUM", "WARTELISTE", "KEINE_ERMAESS_FUER", "TAGESZEIT") 
  TABLESPACE "USERS" ;
 
  CREATE INDEX "MVHS"."I8_V" ON "MVHS"."V" ("KEY_VNR", "UEFACHBER1", "UTAGE", "ZEITTAGE", "GEZAEHLT", "GEZAEHLT_WEIBLICH") 
  TABLESPACE "USERS" ;
 
  CREATE INDEX "MVHS"."I9_V" ON "MVHS"."V" ("KEY_VNR", "FAELLIG_AM", "ANZAHLUNG_FAELLIG_AM", "ANZAHLUNG_FAELLIG_TAGE", "ANZAHLUNG_PROZENT", "KONTO", "KST_KENNZ") 
  TABLESPACE "USERS" ;
 
  CREATE UNIQUE INDEX "MVHS"."IV1" ON "MVHS"."V" ("JAHR", "SEMESTER", "VNR", "STATUS", "KEY_VNR") 
  TABLESPACE "USERS" ;
 
  CREATE INDEX "MVHS"."I_VNR" ON "MVHS"."V" ("VNR") 
  TABLESPACE "USERS" ;
 





CREATE TABLE "MVHS"."STAATSANGEHOERIG" 
   (	"KENNZ" VARCHAR2(3 BYTE), 
	"BEZEICHNUNG" VARCHAR2(60 BYTE), 
	"USR_DATUM" DATE, 
	"IN_DATUM" DATE, 
	"USR_ID" VARCHAR2(15 BYTE), 
	"IN_USER" VARCHAR2(15 BYTE)
   )
  TABLESPACE "USERS" ;
 

  CREATE INDEX "MVHS"."STAATSANGEHOERIG_I1" ON "MVHS"."STAATSANGEHOERIG" ("KENNZ") 
  TABLESPACE "USERS" ;

CREATE TABLE Q_EINZEL_TERMINE
(
	KEY_VTAGE                                          NUMBER(10),
	DATUM                                              DATE,
	WO_TAG                                             VARCHAR2(2),
	WOCHEN_TAG                                         VARCHAR2(10),
	ARBEITSTAG                                         VARCHAR2(1),
	VSTD                                               NUMBER,
	VMIN                                               NUMBER,
	BSTD                                               NUMBER,
	BMIN                                               NUMBER,
	VON_ZEIT                                           VARCHAR2(5),
	BIS_ZEIT                                           VARCHAR2(5),
	VON_BIS_ZEIT                                       VARCHAR2(15),
	KEY_VNR                                            NUMBER(8),
	JAHR                                               VARCHAR2(2),
	SEMESTER                                           VARCHAR2(1),
	STATUS                                             VARCHAR2(1),
	VNR                                                VARCHAR2(12),
	UTEXT1                                             VARCHAR2(40),
	UTEXT                                              VARCHAR2(200),
	BEGDATUM                                           DATE,
	ENDDATUM                                           DATE,
	DOZNR                                              NUMBER(8),
	TXTDOZNR                                           VARCHAR2(480),
	DOZENT                                             VARCHAR2(480),
	TXTKATDOZNR_KURZ                                   VARCHAR2(2000),
	TXTKATDOZNR_LANG                                   VARCHAR2(2000),
	FAECHER                                            VARCHAR2(10),
	TXTFAECHER                                         VARCHAR2(60),
	ORTNR                                              VARCHAR2(5),
	TXTORTNR                                           VARCHAR2(480),
	UORT_HINWEIS                                       VARCHAR2(2000),
	RAUM                                               VARCHAR2(5),
	KEY_RAUM                                           NUMBER(10),
	TXTRAUM                                            VARCHAR2(30),
	NUTZUNG                                            VARCHAR2(1)
);

create sequence seq_maxtnr;

create table ferien
(
	vtage_begin		DATE,
	vtage_ende		DATE,
	bezeichnung		varchar(128),
	gebietskuerzel	varchar(128)
);

create or replace function mvhs_ist_paed_prog( key integer ) return integer as
begin
	return 1;
end;
/
