create table KURSE(
	ID NUMBER(10) not null primary key,
	JAHR VARCHAR2(4) not null,
	HALBJAHR VARCHAR2(1) not null,
	NUMMER VARCHAR2(32) not null,
	BAMF_NUMMER VARCHAR2(32),
	ANFANGS_DATUM DATE not null,
	ENDE_DATUM DATE,
	UNTERRICHTSSTUNDEN NUMBER,
	WOCHENSTUNDEN NUMBER,
	TT_STUNDEN NUMBER,
	SOZ_PAED_STUNDEN NUMBER,
	KURSTAGE VARCHAR2(255),
	FEIERTAGE VARCHAR2(255),
	KURSART VARCHAR2(64),
	KURSTYP VARCHAR2(32),
	KURSABSCHNITT VARCHAR2(32),
	VORKURS VARCHAR2(32),
	NIVEAU VARCHAR2(32),
	LEHRBUCH VARCHAR2(64),
	RAUM VARCHAR2(32),
	UMSATZSTEUER NUMBER,
	KURSGEBUEHR NUMBER,
	FOERDERUNG NUMBER,
	BEMERKUNG VARCHAR(4000),
	MO_ANF DATE,
	MO_END DATE,
	MO_PAUS_ANF DATE,
	MO_PAUS_END DATE,
	DI_ANF DATE,
	DI_END DATE,
	DI_PAUS_ANF DATE,
	DI_PAUS_END DATE,
	MI_ANF DATE,
	MI_END DATE,
	MI_PAUS_ANF DATE,
	MI_PAUS_END DATE,
	DO_ANF DATE,
	DO_END DATE,
	DO_PAUS_ANF DATE,
	DO_PAUS_END DATE,
	FR_ANF DATE,
	FR_END DATE,
	FR_PAUS_ANF DATE,
	FR_PAUS_END DATE,
	SA_ANF DATE,
	SA_END DATE,
	SA_PAUS_ANF DATE,
	SA_PAUS_END DATE,
	SO_ANF DATE,
	SO_END DATE,
	SO_PAUS_ANF DATE,
	SO_PAUS_END DATE
);
create index ANFANG_IDX on KURSE(
	ANFANGS_DATUM
);
create unique index JAHR_NUMMER_IDX on KURSE(
	NUMMER, HALBJAHR, JAHR
);

create table SCHUELER(
	ID NUMBER(10) not null primary key,
	AENDERUNGSDATUM DATE,
	ANMELDE_DATUM DATE,
	TEILNEHMER_NUMMER VARCHAR2(255),
	ANREDE VARCHAR2(32),
	GESCHLECHT VARCHAR2(1),
	NACHNAME VARCHAR2(64) not null,
	VORNAME VARCHAR2(64),
	WOHNUNG VARCHAR2(64),
	STRASSE VARCHAR2(128),
	LAND VARCHAR2(3),
	PLZ VARCHAR2(16),
	ORT VARCHAR2(64),
	TEL_PRIV VARCHAR2(64),
	TEL_BUERO VARCHAR2(64),
	TEL_MOBIL VARCHAR2(64),
	TEL_FAX VARCHAR2(64),
	E_MAIL VARCHAR2(64),
	GEBURTSDATUM DATE,
	GEBURTSORT VARCHAR2(64),
	NATIONALITAET VARCHAR2(64),
	AUSLAENDER_STATUS VARCHAR2(64),
	BERUF VARCHAR2(64),
	TAETIGKEIT VARCHAR2(64),
	WOHER VARCHAR2(255),
	PRUEFUNGEN VARCHAR2(255),
	EINSTUFUNG VARCHAR2(255),
	BEMERKUNG VARCHAR(4000),
	ISCED_LEVEL VARCHAR2(3),
	SCHULJAHRE NUMBER(5),
	KURS_MODUL NUMBER(5),
	KURSART VARCHAR2(64),
	SCHREIBFAEHIGKEIT NUMBER(5),
	AUSWEIS_NUMMER VARCHAR2(255),
	BAMF_NUMMER VARCHAR2(255),
	ABH_NUMMER VARCHAR2(255),
	BVA_NUMMER VARCHAR2(255),
	AZ_GRUNDSICHERUNG VARCHAR2(255),
	ABGESCHLOSSEN VARCHAR2(1),
	BANK_INHABER VARCHAR2(128),
	BANK_KONTO VARCHAR2(32),
	BANK_BLZ VARCHAR2(16),
	BANK_NAME VARCHAR2(128)
);
create index SCHUELER_NAME_IDX on SCHUELER(
	NACHNAME, VORNAME
);

create table ANWESENHEITEN(
	SCHUELER_ID NUMBER(10) not null references SCHUELER,
	KURS_ID NUMBER(10) not null references KURSE,
	DATUM DATE,
	ENTSCHULDIGT VARCHAR2(1)
);
create unique index ANWESENHEITEN0 on ANWESENHEITEN(
	SCHUELER_ID, KURS_ID, DATUM
);
create index KURS_ID on ANWESENHEITEN(
	KURS_ID
);

create table KURSSCHUELER(
	ID NUMBER(10) not null primary key,
	KURS_ID NUMBER(10) not null references KURSE,
	SCHUELER_ID NUMBER(10) not null references SCHUELER,
	ANFANG DATE,
	ENDE DATE,
	BEMERKUNG VARCHAR(4000),
	KOSTENBETEILIGUNG VARCHAR2(32),
	ANTRAG_KOSTENBEFREIUNG VARCHAR2(1),
	ORDNUNGSGEMAESS VARCHAR2(1),
	FAHRTKOSTENBEWILLIGUNG VARCHAR2(1)
);
create index KURS_SCHUELER_IDX on KURSSCHUELER(
	KURS_ID, SCHUELER_ID
);
create index SCHUELER_ID on KURSSCHUELER(
	SCHUELER_ID
);

create table BEZAHLUNG(
	ID NUMBER(10) not null,
	KURS_SCHUELER_ID NUMBER(10) not null references KURSSCHUELER,
	DATUM DATE not null,
	BESCHREIBUNG VARCHAR2(64) not null,
	ZAHLUNGSART VARCHAR2(16),
	BETRAG NUMBER not null
);
create unique index BEZAHLUNG0 on BEZAHLUNG(
	ID
);
create index KURS_SCHUELER_ID on BEZAHLUNG(
	KURS_SCHUELER_ID
);

create table CONFIG(
	ENTRY_NAME VARCHAR2(32) not null,
	INT_VALUE NUMBER(10),
	STRING_VALUE VARCHAR2(255)
);
create unique index CONFIG0 on CONFIG(
	ENTRY_NAME
);

create table FERIEN(
	ANFANG DATE not null,
	ENDE DATE not null,
	BEZEICHNUNG VARCHAR2(255) not null
);
create unique index FERIEN0 on FERIEN(
	ANFANG
);

create table LEHRBUECHER(
	ID NUMBER(10) not null primary key,
	GRUPPE VARCHAR2(50) not null,
	TITEL VARCHAR2(200) not null,
	UNTERTITEL VARCHAR2(200),
	VERLAG VARCHAR2(200)
);
create index BUCH_GRUPPE_TITEL_IDX on LEHRBUECHER(
	GRUPPE, TITEL
);

create table KURSBUECHER(
	KURS_ID NUMBER(10) not null references KURSE,
	BUCH_ID NUMBER(10) not null references LEHRBUECHER
);
create index BUCH_ID on KURSBUECHER(
	BUCH_ID
);
create unique index KURSBUECHER0 on KURSBUECHER(
	KURS_ID, BUCH_ID
);

create table LEHRER(
	WOHNUNG VARCHAR2(64),
	STRASSE VARCHAR2(128),
	LAND VARCHAR2(3),
	PLZ VARCHAR2(16),
	ORT VARCHAR2(64),
	TEL_PRIV VARCHAR2(64),
	TEL_BUERO VARCHAR2(64),
	TEL_MOBIL VARCHAR2(64),
	TEL_FAX VARCHAR2(64),
	E_MAIL VARCHAR2(128),
	GEBURTSDATUM DATE,
	GEBURTSORT VARCHAR2(64),
	NATIONALITAET VARCHAR2(64),
	AKAD_TITEL VARCHAR2(32),
	SV_ABSCHLUSS DATE,
	DAF_ERFAHRUNG DATE,
	EINSTIEG DATE,
	VERTRAG DATE,
	BAMF_NUMMER VARCHAR2(64),
	BEMERKUNG VARCHAR(4000),
	ID NUMBER(10) not null primary key,
	ANREDE VARCHAR2(32),
	GESCHLECHT VARCHAR2(1),
	NACHNAME VARCHAR2(64) not null,
	VORNAME VARCHAR2(64)
);
create index LEHRER_NAME_IDX on LEHRER(
	NACHNAME, VORNAME
);

create table KURSLEHRER(
	ID NUMBER(10) not null primary key,
	LEHRER_ID NUMBER(10) not null references LEHRER,
	KURS_ID NUMBER(10) not null references KURSE,
	ANFANG DATE,
	ENDE DATE,
	TEAM_TEACHER VARCHAR2(1),
	SOZ_PAED VARCHAR2(1)
);
create index KURS_LEHRER_IDX on KURSLEHRER(
	LEHRER_ID, KURS_ID
);
create index LEHRER_ID on KURSLEHRER(
	LEHRER_ID
);

create table LEHRZEITEN(
	ID NUMBER(10) not null,
	LEHRER_KURS_ID NUMBER(10) not null references KURSLEHRER,
	DATUM DATE not null,
	START_ZEIT DATE not null,
	ENDE_ZEIT DATE not null,
	PAUSE_ANFANG DATE not null,
	PAUSE_ENDE DATE not null
);
create index LEHRER_KURS_ID on LEHRZEITEN(
	LEHRER_KURS_ID
);
create unique index LEHRZEITEN0 on LEHRZEITEN(
	ID
);

create table PRUEFUNGEN(
	ID NUMBER(10) not null primary key,
	PRUEFUNG VARCHAR2(128) not null,
	DATUM DATE not null,
	JAHR VARCHAR2(4) not null,
	DATUM_STRING VARCHAR2(10) not null
);
create unique index PRUEFUNGS_IDX on PRUEFUNGEN(
	DATUM, PRUEFUNG
);

create table PRUEFSCHUELER(
	ID NUMBER(10) not null,
	PRUEF_ID NUMBER(10) not null references PRUEFUNGEN,
	SCHUELER_ID NUMBER(10) not null references SCHUELER,
	BEMERKUNG VARCHAR(4000),
	BESTANDEN VARCHAR2(1)
);
create unique index PRUEFSCHUELER0 on PRUEFSCHUELER(
	ID
);
create index PRUEF_ID on PRUEFSCHUELER(
	PRUEF_ID
);

@tables_upd01.sql
@tables_upd02.sql
@tables_upd03.sql
@tables_upd04.sql
