alter table SCHUELER add
(
	AENDERUNG_VON	VARCHAR2(255),
	WDH_BAMF_NUMMER	VARCHAR2(255),
	AP_NAME			VARCHAR2(64),
	AP_VORNAME		VARCHAR2(64),
	AP_ORGANISATION	VARCHAR2(255),
	AP_STRASSE		VARCHAR2(255),
	AP_PLZ			VARCHAR2(16),
	AP_ORT			VARCHAR2(255),
	AP_TELEFON		VARCHAR2(32),
	AP_FAX			VARCHAR2(32),
	AP_EMAIL		VARCHAR2(32),
	AP_INFO			VARCHAR(255)
);

alter table KURSE add
(
	AENDERUNGSDATUM	DATE,
	AENDERUNG_VON	VARCHAR2(255)
);

alter table KURSSCHUELER add
(
	STORNO 			DATE,
	ANMELDE_DATUM	DATE,
	KOSTENBEFREIUNG	DATE
);

alter table PRUEFUNGEN add
(
	AUFSICHT		VARCHAR2(255),
	ANSPRECHPARTNER	VARCHAR2(255),
	RAUM			VARCHAR2(32)
);

alter table PRUEFSCHUELER add
(
	KOSTENBETEILIGUNG	VARCHAR2(32)
);

alter table KURSBUECHER add
(
	KURS_TITEL			VARCHAR2(255)
);

